apiVersion: apps/v1
kind: Deployment
metadata:
  name: crapi-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: crapi-web
  template:
    metadata:
      labels:
        app: crapi-web
    spec:
      containers:
      - name: crapi-web
        image: crapi/crapi-web:develop
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "500m"
          requests:
            cpu: 256m
        env:
        - name: COMMUNITY_SERVICE
          value: "crapi-community:8087"
        - name: IDENTITY_SERVICE
          value: "crapi-identity:8080"
        - name: WORKSHOP_SERVICE
          value: "crapi-workshop:8000"
        - name: MAILHOG_WEB_SERVICE
          value: "mailhog:8025"
        - name: TLS_ENABLED
          value: "false"

