apiVersion: v1
kind: Service
metadata:
  name: crapi-web
  labels:
    app: crapi-web
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "false"  # Set to "true" if you want an internal LB
    service.beta.kubernetes.io/azure-load-balancer-resource-group: "ppp" # Optional, only if LB should be created in a different RG
spec:
  type: LoadBalancer
  selector:
    app: crapi-web
  ports:
    - port: 80
      nodePort: 30080
      targetPort: 80
      protocol: TCP
      name: nginx

