apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  labels:
    app: postgresdb
spec:
  storageClassName: "default"  # or leave empty if "default" points to a suitable class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

