apiVersion: v1
kind: Pod
metadata:
  name: pod-with-capabilities
  namespace: opa-test
spec:
  containers:
    - name: demo-container
      image: alpine
      command: ["sleep", "3600"]
      securityContext:
        capabilities:
          add: ["NET_ADMIN", "SYS_TIME"]
          drop: ["AUDIT_WRITE", "MKNOD"]

